### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Nevon** [Nevon/Ubuntu-Dota-2-Match-Ticker#15]
### 0.1.0 Initial Release
- [x] Make sure Mixpanel events have a unique device ID #11
- [x] "No matches" messages for different filters #13 
- [x] Observe request status when displaying "No matches" message #12 
- [x] Test on a device/emulator
- [x] Fix icon position. #20
- [x] Set boot splash #14
- [x] Handle missing league info #19 
### 0.2.0
- [ ] Save favorite filter
- [ ] Filter on favorite teams #7
- [ ] Create reminder event for upcoming match #4
